// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Delband {
    from:       string;
    to:         string;
    net_weight: string;
    cpu_weight: string;
}
