import { Authorization } from "./eosio";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Delegatebw {
    transactionId: string;
    actionIndex: number;
    account: string;
    name: string;
    authorization: Authorization[];
    data: DelegatebwData;
}

export interface DelegatebwData {
    from: string;
    receiver: string;
    stake_net_quantity: string;
    stake_cpu_quantity: string;
    transfer: number;
}
