// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Eosio {
    version: string;
    types: Type[];
    structs: Struct[];
    actions: Action[];
    tables: Table[];
    ricardian_clauses: RicardianClause[];
    error_messages: any[];
    abi_extensions: any[];
}

export interface Action {
    name: string;
    type: string;
    ricardian_contract: string;
}

export interface RicardianClause {
    id: string;
    body: string;
}

export interface Struct {
    name: string;
    base: Base;
    fields: Field[];
}

export enum Base {
    BlockchainParameters = "blockchain_parameters",
    Empty = "",
}

export interface Field {
    name: string;
    type: string;
}

export interface Table {
    name: string;
    index_type: string;
    key_names: string[];
    key_types: string[];
    type: string;
}

export interface Type {
    new_type_name: string;
    type: string;
}

// Extras

export interface Authorization {
    actor: string;
    permission: string;
}

export interface Payload<Data = any> {
    transactionId: string;
    actionIndex: number;
    account: string;
    name: string;
    authorization: Authorization[];
    data: Data;
}
