// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Proposal {
    proposal_name: string;
    proposer:      string;
    title:         string;
    proposal_json: string;
    created_at:    string;
    expires_at:    string;
}
