// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Table {
    rows: Row[];
    more: boolean;
}

export interface Row {
    id:            number;
    proposal_name: string;
    voter:         string;
    vote:          number;
    vote_json:     string;
    updated_at:    string;
}
