// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GetTableRows<T = any> {
    rows: T[];
    more: boolean;
}
