// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Userres {
    ram_bytes:     number;
    cpu_weight:    string;
    net_weight:    string;
    owner:         string;
}
